apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
  labels:
    app: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: greeting
          image: rest-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  labels:
    app: greeting
spec:
  selector:
    app: greeting
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: greeting-vs
spec:
  hosts:
    - "greeting.172.19.0.6.nip.io"
  gateways:
    - greeting-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: greeting-service
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
     name: greeting-gateway
spec:
   selector: 
      istio: ingressgateway
   servers:
       - port:
           number: 80
           name: http2
           protocol: HTTP
         hosts:
          - "greeting.172.19.0.6.nip.io"