---
# Enhanced RequestAuthentication for book-info service
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: book-info-request-authentication
  namespace: default
spec:
  selector:
    matchLabels:
      app: book-info
  jwtRules:
  - issuer: "http://keycloak.172.19.0.6.nip.io/realms/Istio"
    jwksUri: "http://keycloak.172.19.0.6.nip.io/realms/Istio/protocol/openid-connect/certs"
    audiences: ["client", "api-client"]
    forwardOriginalToken: true
---
# # RequestAuthentication for greeting-service (if it needs to validate incoming JWTs)
# apiVersion: security.istio.io/v1beta1
# kind: RequestAuthentication
# metadata:
#   name: greeting-service-request-authentication
#   namespace: default
# spec:
#   selector:
#     matchLabels:
#       app: greeting-service
#   jwtRules:
#   - issuer: "http://keycloak.172.19.0.6.nip.io/realms/Istio"
#     jwksUri: "http://keycloak.172.19.0.6.nip.io/realms/Istio/protocol/openid-connect/certs"
#     audiences: ["client", "api-client"]
#     forwardOriginalToken: true